# Atividade 1 - Pandas Data Analysis

**Discente:** Gabriel Martins

## Creating, Reading and Writing

In [ ]:
#@title Configurações

import pandas as pd
import polars as pl

from google.colab import drive
drive.mount('/content/drive')

wine_reviews = pd.read_csv("/content/drive/MyDrive/winemag.csv", index_col=0)
wine_reviews_pl = pl.read_csv("/content/drive/MyDrive/winemag.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
wine_reviews_pl.describe()

shape: (9, 15)
┌────────────┬────────────┬───────────┬────────────┬───┬───────────┬───────────┬──────────┬────────┐
│ statistic  ┆            ┆ country   ┆ descriptio ┆ … ┆ taster_tw ┆ title     ┆ variety  ┆ winery │
│ ---        ┆ ---        ┆ ---       ┆ n          ┆   ┆ itter_han ┆ ---       ┆ ---      ┆ ---    │
│ str        ┆ f64        ┆ str       ┆ ---        ┆   ┆ dle       ┆ str       ┆ str      ┆ str    │
│            ┆            ┆           ┆ str        ┆   ┆ ---       ┆           ┆          ┆        │
│            ┆            ┆           ┆            ┆   ┆ str       ┆           ┆          ┆        │
╞════════════╪════════════╪═══════════╪════════════╪═══╪═══════════╪═══════════╪══════════╪════════╡
│ count      ┆ 129971.0   ┆ 129908    ┆ 129971     ┆ … ┆ 98758     ┆ 129971    ┆ 129970   ┆ 129971 │
│ null_count ┆ 0.0        ┆ 63        ┆ 0          ┆ … ┆ 31213     ┆ 0         ┆ 1        ┆ 0      │
│ mean       ┆ 64985.0    ┆ null      ┆ null       ┆ … ┆ null      ┆ null      ┆ null     ┆ null   │
│ std        ┆ 37519.5402 ┆ null      ┆ null       ┆ … ┆ null      ┆ null      ┆ null     ┆ null   │
│            ┆ 56         ┆           ┆            ┆   ┆           ┆           ┆          ┆        │
│ min        ┆ 0.0        ┆ Argentina ┆ "Chremisa, ┆ … ┆ @AnneInVi ┆ 1+1=3     ┆ Abouriou ┆ 1+1=3  │
│            ┆            ┆           ┆ " the      ┆   ┆ no        ┆ 2008 Rosé ┆          ┆        │
│            ┆            ┆           ┆ ancient    ┆   ┆           ┆ Cabernet  ┆          ┆        │
│            ┆            ┆           ┆ name o…    ┆   ┆           ┆ Sauvi…    ┆          ┆        │
│ 25%        ┆ 32493.0    ┆ null      ┆ null       ┆ … ┆ null      ┆ null      ┆ null     ┆ null   │
│ 50%        ┆ 64985.0    ┆ null      ┆ null       ┆ … ┆ null      ┆ null      ┆ null     ┆ null   │
│ 75%        ┆ 97478.0    ┆ null      ┆ null       ┆ … ┆ null      ┆ null      ┆ null     ┆ null   │
│ max        ┆ 129970.0   ┆ Uruguay   ┆ “Wow” is   ┆ … ┆ @worldwin ┆ Štoka     ┆ Žilavka  ┆ Štoka  │
│            ┆            ┆           ┆ the first  ┆   ┆ eguys     ┆ 2011      ┆          ┆        │
│            ┆            ┆           ┆ word that  ┆   ┆           ┆ Izbrani   ┆          ┆        │
│            ┆            ┆           ┆ c…         ┆   ┆           ┆ Teran     ┆          ┆        │
│            ┆            ┆           ┆            ┆   ┆           ┆ (Kras…    ┆          ┆        │
└────────────┴────────────┴───────────┴────────────┴───┴───────────┴───────────┴──────────┴────────┘

In [ ]:
wine_reviews.describe().T

           count       mean        std   min   25%   50%   75%     max
points  129971.0  88.447138   3.039730  80.0  86.0  88.0  91.0   100.0
price   120975.0  35.363389  41.022218   4.0  17.0  25.0  42.0  3300.0

In [ ]:
wine_reviews.describe(include='object').T

,count,unique,top,freq
country,129908,43,US,54504
description,129971,119955,"Seductively tart in lemon pith, cranberry and ...",3
designation,92506,37979,Reserve,2009
province,129908,425,California,36247
region_1,108724,1229,Napa Valley,4480
region_2,50511,17,Central Coast,11065
taster_name,103727,19,Roger Voss,25514
taster_twitter_handle,98758,15,@vossroger,25514
title,129971,118840,Gloria Ferrer NV Sonoma Brut Sparkling (Sonoma...,11
variety,129970,707,Pinot Noir,13272
winery,129971,16757,Wines & Winemakers,222

In [ ]:
pd.crosstab(wine_reviews_pl['taster_name'], wine_reviews_pl['variety']).reset_index()

col_0,row_0,Abouriou,Agiorgitiko,Aglianico,Aidani,Airen,Albana,Albanello,Albariño,Aleatico,...,Yapincak,Zelen,Zibibbo,Zierfandler,Zierfandler-Rotgipfler,Zinfandel,Zlahtina,Zweigelt,Çalkarası,Žilavka
0,Alexander Peartree,0,0,1,0,0,0,0,3,0,...,0,0,0,0,0,0,0,0,0,0
1,Anna Lee C. Iijima,0,0,0,0,0,0,0,3,0,...,0,1,0,0,0,0,0,2,0,0
2,Anne Krebiehl MW,0,0,0,0,0,0,0,0,0,...,0,0,0,12,5,0,0,130,0,0
3,Carrie Dykes,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,Christina Pickard,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Fiona Adams,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Jeff Jenssen,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,1
7,Jim Gordon,0,0,5,0,0,0,0,13,0,...,0,0,0,0,0,434,0,0,0,0
8,Joe Czerwinski,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,3,0,0,0,0
9,Kerin O’Keefe,0,0,178,0,0,16,1,0,2,...,0,0,17,0,0,0,0,0,0,0
10,Lauren Buzzeo,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,Matt Kettmann,0,0,3,0,0,0,0,41,0,...,0,0,0,0,0,175,0,0,0,0
12,Michael Schachner,0,0,0,0,3,0,0,343,0,...,0,0,0,0,0,0,0,0,0,0
13,Mike DeSimone,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,2,0
14,Paul Gregutt,0,0,0,0,0,0,0,13,0,...,0,0,0,0,0,151,0,2,0,0
15,Roger Voss,2,0,0,0,0,0,0,0,0,...,0,0,0,4,0,0,0,71,0,0
16,Sean P. Sullivan,0,0,0,0,0,0,0,10,0,...,0,0,0,0,0,17,0,3,0,0
17,Susan Kostrzewa,0,63,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
18,Virginie Boone,1,0,6,0,0,0,0,17,0,...,0,0,0,0,0,800,0,0,0,0

In [ ]:
wine_reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 129971 entries, 0 to 129970
Data columns (total 13 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   country                129908 non-null  object
 1   description            129971 non-null  object
 2   designation            92506 non-null   object
 3   points                 129971 non-null  int64
 4   price                  120975 non-null  float64
 5   province               129908 non-null  object
 6   region_1               108724 non-null  object
 7   region_2               50511 non-null   object
 8   taster_name            103727 non-null  object
 9   taster_twitter_handle  98758 non-null   object
 10  title                  129971 non-null  object
 11  variety                129970 non-null  object
 12  winery                 129971 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 13.9+ MB

### Questão 1
Leia o dataset de revisões de vinhos em um DataFrame chamado `reviews`. Escreva um código para salvar uma amostra aleatoria de 100 reviews deste DataFrame como um arquivo csv com o nome `100samples_wine_reviews`.

In [ ]:
#@title Resposta Q1

sample = wine_reviews.sample(n=100, random_state=42)
sample.to_csv('100samples_wine_reviews.csv', index=False)
sample.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
77718,Australia,"Possibly a little sweet, this is a soft, easyg...",NaN,83,5.0,Australia Other,South Eastern Australia,NaN,Joe Czerwinski,@JoeCz,Banrock Station 2006 Chardonnay (South Eastern...,Chardonnay,Banrock Station
67681,France,"A soft, almost off dry wine that is full in th...",Réserve,85,12.0,Rhône Valley,Côtes du Rhône,NaN,Roger Voss,@vossroger,Cellier des Dauphins 2015 Réserve Rosé (Côtes ...,Rosé,Cellier des Dauphins
69877,Spain,Generic white-fruit aromas of peach and apple ...,Estate Grown & Bottled,86,9.0,Northern Spain,Rueda,NaN,Michael Schachner,@wineschach,Esperanza 2013 Estate Grown & Bottled Verdejo-...,Verdejo-Viura,Esperanza
46544,US,This is the winery's best Nebula in years. Whi...,Nebula,87,29.0,California,Paso Robles,Central Coast,NaN,NaN,Midnight 2010 Nebula Cabernet Sauvignon (Paso ...,Cabernet Sauvignon,Midnight
186,US,This is a very rich Pinot whose primary virtue...,Wiley Vineyard,88,40.0,California,Anderson Valley,NaN,NaN,NaN,Harrington 2006 Wiley Vineyard Pinot Noir (And...,Pinot Noir,Harrington

## Indexing, Selecting and Assigning

### Questão 2
Crie uma variável `df` contendo as colunas `country`, `province`, `region_1` e `region_2` para as linhas `0`, `1`, `10`, e `100`.

In [ ]:
#@title Resposta Q2

df = wine_reviews.loc[[0, 1, 10, 100], ['country', 'province', 'region_1', 'region_2']]
df

      country           province      region_1      region_2
0       Italy  Sicily & Sardinia          Etna           NaN
1    Portugal              Douro           NaN           NaN
10         US         California   Napa Valley          Napa
100        US           New York  Finger Lakes  Finger Lakes

### Questão 3
Crie uma variável `df` contendo as colunas `country` e `variety` dos 100 primeiros registros.

Dica: você pode usar `loc` ou `iloc`. Lembre-se, em `iloc` o primeiro elemento do intervalo é incluído e o último é excluído, enquanto `loc` os índices é inclusivo.

In [ ]:
#@title Resposta Q3

df = wine_reviews.iloc[0:100, [0, 11]]
df

     country                   variety
0      Italy               White Blend
1   Portugal            Portuguese Red
2         US                Pinot Gris
3         US                  Riesling
4         US                Pinot Noir
..       ...                       ...
95    France                     Gamay
96    France                     Gamay
97        US                  Riesling
98     Italy                Sangiovese
99        US  Bordeaux-style Red Blend

[100 rows x 2 columns]

### Questão 4
Crie um DataFrame `italian_wines` contendo os reviews de vinhos feitos em `Italy`. Dica: `reviews_country` igual a?

In [ ]:
#@title Resposta Q4

reviews_country = wine_reviews['country'] == 'Italy'
italian_wines = wine_reviews[reviews_country]
italian_wines.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì

### Questão 5
Crie um DataFrame `top_oceania_wines` contendo todos os reviews com pelo menos 95 pontos (dos 100 pontos) para vinhos da Australia ou New Zealand.

In [ ]:
#@title Resposta Q5

oceania_wines = wine_reviews['country'].isin(['Australia', 'New Zealand'])
top_oceania_wines = wine_reviews[oceania_wines & (wine_reviews['points'] >= 95)]
top_oceania_wines.sort_values(by='points', ascending=False)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
345,Australia,This wine contains some material over 100 year...,Rare,100,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,Muscat,Chambers Rosewood Vineyards
109427,Australia,This wine is dark brown in hue with a greenish...,Rare,99,300.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscadelle...,Muscadelle,Chambers Rosewood Vineyards
56953,Australia,"This inky, embryonic wine deserves to be cella...",Grange,99,850.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2010 Grange Shiraz (South Australia),Shiraz,Penfolds
34502,Australia,This prodigious wine showcases Barossa's abili...,The Relic,98,135.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Standish 2006 The Relic Shiraz (Barossa Valley),Shiraz,Standish
77028,Australia,This has all the size and weight you've come t...,Grange,98,850.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2008 Grange Shiraz (South Australia),Shiraz,Penfolds
346,Australia,"This deep brown wine smells like a damp, mossy...",Rare,98,350.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscadelle...,Muscadelle,Chambers Rosewood Vineyards
67096,Australia,Just a tiny serving of this dark nectar will l...,Calliope Rare,98,86.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,R.L. Buller & Son NV Calliope Rare Tokay (Ruth...,Tokay,R.L. Buller & Son
122939,Australia,Full-bodied and plush yet vibrant and imbued w...,The Factor,98,125.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2013 The Factor Shiraz (Barossa Valley),Shiraz,Torbreck
348,Australia,Deep mahogany. Dried fig and black tea on the ...,Grand,97,100.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Grand Muscat (R...,Muscat,Chambers Rosewood Vineyards
349,Australia,"RunRig is always complex, and the 2012 doesn't...",RunRig,97,225.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,Torbreck 2012 RunRig Shiraz-Viognier (Barossa),Shiraz-Viognier,Torbreck
56956,Australia,You may have to scour the country to secure so...,Andelmonde,97,95.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Standish 2012 Andelmonde Shiraz (Barossa Valley),Shiraz,Standish
77037,Australia,Winemaker Dave Powell is no longer with Torbre...,RunRig,96,225.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2007 RunRig Shiraz-Viognier (Barossa ...,Shiraz-Viognier,Torbreck
87128,Australia,"This full-bodied, muscular Shiraz is built for...",Amery Vineyard Block 6,96,120.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Kay Brothers 2012 Amery Vineyard Block 6 Shira...,Shiraz,Kay Brothers
77036,Australia,RWT (unromantically derived from “Red Wine Tri...,RWT,96,150.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Penfolds 2009 RWT Shiraz (Barossa Valley),Shiraz,Penfolds
59977,Australia,This is a top example of the classic Australia...,The Peake,96,150.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Hickinbotham 2013 The Peake Cabernet-Shiraz (M...,Cabernet-Shiraz,Hickinbotham
56957,Australia,Thorn Clarke has taken its Shiraz to a new lev...,Ron Thorn Single Vineyard,96,89.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,Thorn Clarke 2012 Ron Thorn Single Vineyard Sh...,Shiraz,Thorn Clarke
56959,Australia,Is this the Yin to Grange's Yang? The wines ar...,Hill of Grace,96,820.0,South Australia,Eden Valley,NaN,Joe Czerwinski,@JoeCz,Henschke 2010 Hill of Grace Shiraz (Eden Valley),Shiraz,Henschke
109434,Australia,D'Arenberg's lineup of single-vineyard Shiraze...,The Swinging Malaysian Single Vineyard,96,85.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,D'Arenberg 2010 The Swinging Malaysian Single ...,Shiraz,D'Arenberg
39961,Australia,"As unevolved as they are, the dense and multil...",Grange,96,185.0,South Australia,South Australia,NaN,NaN,NaN,Penfolds 1996 Grange Shiraz (South Australia),Shiraz,Penfolds
122421,Australia,"Despite this wine's weight and richness, it re...",Amon-Ra Unfiltered,96,110.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Glaetzer 2010 Amon-Ra Unfiltered Shiraz (Baros...,Shiraz,Glaetzer
34506,Australia,If Standish's Relic is the feminine side of Sh...,The Standish Single Vineyard,96,135.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Standish 2005 The Standish Single Vineyard Shi...,Shiraz,Standish
83357,Australia,A throwback to the monster Shiraz style of old...,Grange,96,500.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2004 Grange Shiraz (South Australia),Shiraz,Penfolds
99340,Australia,"This rich, opulent wine carries its massive oa...",Les Amis,95,185.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2013 Les Amis Grenache (Barossa Valley),Grenache,Torbreck
84815,Australia,The Factor is always one of Torbreck's biggest...,The Factor,95,125.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,Torbreck 2012 The Factor Shiraz (Barossa),Shiraz,Torbreck
99330,Australia,This Cabernet equivalent to Grange has explode...,Bin 707,95,500.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2014 Bin 707 Cabernet Sauvignon (Sout...,Cabernet Sauvignon,Penfolds
99318,Australia,"From vines planted in 1912, this has been an i...",Mount Edelstone Vineyard,95,200.0,South Australia,Eden Valley,NaN,Joe Czerwinski,@JoeCz,Henschke 2014 Mount Edelstone Vineyard Shiraz ...,Shiraz,Henschke
98386,Australia,One of the more approachable of the d'Arenberg...,Little Venice Single Vineyard,95,85.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,D'Arenberg 2010 Little Venice Single Vineyard ...,Shiraz,D'Arenberg
91851,New Zealand,"This full-bodied, richly tannic wine delivers....",Homage,95,100.0,Hawke's Bay,NaN,NaN,Joe Czerwinski,@JoeCz,Trinity Hill 2013 Homage Syrah (Hawke's Bay),Syrah,Trinity Hill
122430,Australia,These blends are traditional in Australia—they...,Anaperenna,95,80.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Glaetzer 2010 Anaperenna Shiraz-Cabernet Sauvi...,Shiraz-Cabernet Sauvignon,Glaetzer
87143,Australia,"This is wonderfully complex and aromatic, with...",St. Andrews Single Vineyard Release,95,60.0,South Australia,Clare Valley,NaN,Joe Czerwinski,@JoeCz,Wakefield 2012 St. Andrews Single Vineyard Rel...,Shiraz,Wakefield
87137,Australia,Perhaps the best young wine I've tasted from M...,NaN,95,84.0,Western Australia,Margaret River,NaN,Joe Czerwinski,@JoeCz,Moss Wood 2011 Cabernet Sauvignon (Margaret Ri...,Cabernet Sauvignon,Moss Wood
122507,New Zealand,"This blend of Cabernet Sauvignon (62.5%), Merl...",SQM Gimblett Gravels Cabernets/Merlot,95,79.0,Hawke's Bay,NaN,NaN,Joe Czerwinski,@JoeCz,Squawking Magpie 2014 SQM Gimblett Gravels Cab...,Bordeaux-style Red Blend,Squawking Magpie
84816,Australia,"Nashwauk is Kaesler's McLaren Vale project, fi...",Beacon,95,145.0,South Australia,McLaren Vale,NaN,Joe Czerwinski,@JoeCz,Nashwauk 2010 Beacon Shiraz (McLaren Vale),Shiraz,Nashwauk
16538,Australia,"Rich, dense and intense, this is a big, muscul...",The Family Tree,95,65.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Lambert 2013 The Family Tree Shiraz (Barossa V...,Shiraz,Lambert
77046,Australia,With aromas and flavors that range widely from...,The Factor,95,125.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2007 The Factor Shiraz (Barossa Valley),Shiraz,Torbreck
77044,Australia,The fruit for this offering comes from the Gre...,R Reserve,95,105.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Kilikanoon 2009 R Reserve Shiraz (Barossa Valley),Shiraz,Kilikanoon
77042,Australia,This is likely the most ageworthy Shiraz winem...,Eligo,95,100.0,South Australia,Barossa,NaN,Joe Czerwinski,@JoeCz,John Duval Wines 2010 Eligo Shiraz (Barossa),Shiraz,John Duval Wines
28573,Australia,Astralis has become one of Australia's top col...,Astralis,95,350.0,South Australia,Clarendon,NaN,Joe Czerwinski,@JoeCz,Clarendon Hills 2005 Astralis Syrah (Clarendon),Syrah,Clarendon Hills
76392,Australia,When the alcohol levels are reined in to appro...,Georgia's Paddock,95,85.0,Victoria,Heathcote,NaN,Joe Czerwinski,@JoeCz,Jasper Hill 2012 Georgia's Paddock Shiraz (Hea...,Shiraz,Jasper Hill
356,Australia,"Dusty, firm, powerful: just a few apt descript...",Georgia's Paddock,95,85.0,Victoria,Heathcote,NaN,Joe Czerwinski,@JoeCz,Jasper Hill 2013 Georgia's Paddock Shiraz (Hea...,Shiraz,Jasper Hill
360,Australia,Bacon and tapenade elements merge easily on th...,Descendant,95,125.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Torbreck 2012 Descendant Shiraz-Viognier (Baro...,Shiraz-Viognier,Torbreck
59984,Australia,"This is a throwback to those brash, flavor-exu...",One,95,95.0,South Australia,Langhorne Creek,NaN,Joe Czerwinski,@JoeCz,Heartland 2013 One Red (Langhorne Creek),Red Blend,Heartland
365,Australia,The Taylor family selected Clare Valley for it...,St. Andrews Single Vineyard Release,95,60.0,South Australia,Clare Valley,NaN,Joe Czerwinski,@JoeCz,Wakefield 2013 St. Andrews Single Vineyard Rel...,Shiraz,Wakefield
45809,Australia,The 2007 Astralis impresses for its combinatio...,Astralis,95,225.0,South Australia,Clarendon,NaN,Joe Czerwinski,@JoeCz,Clarendon Hills 2007 Astralis Syrah (Clarendon),Syrah,Clarendon Hills
39962,Australia,"Seamless luxury from stem to stern, this ‘baby...",RWT,95,70.0,South Australia,Barossa Valley,NaN,NaN,NaN,Penfolds 1998 RWT Shiraz (Barossa Valley),Shiraz,Penfolds
39059,Australia,The Taylor family selected Clare Valley for it...,St. Andrews Single Vineyard Release,95,60.0,South Australia,Clare Valley,NaN,Joe Czerwinski,@JoeCz,Wakefield 2013 St. Andrews Single Vineyard Rel...,Shiraz,Wakefield
38988,Australia,Penfolds Bin 707 has leapt in quality over the...,Bin 707,95,200.0,South Australia,South Australia,NaN,Joe Czerwinski,@JoeCz,Penfolds 2009 Bin 707 Cabernet Sauvignon (Sout...,Cabernet Sauvignon,Penfolds
14354,Australia,This wine's concentrated dark fruit shows in t...,Old Vine,95,60.0,South Australia,Barossa Valley,NaN,Joe Czerwinski,@JoeCz,Kaesler 2006 Old Vine Shiraz (Barossa Valley),Shiraz,Kaesler
67101,Australia,"This Muscat is the color of dark coffee, with ...",Rare,95,300.0,Victoria,Rutherglen,NaN,Joe Czerwinski,@JoeCz,Chambers Rosewood Vineyards NV Rare Muscat (Ru...,Muscat,Chambers Rosewood Vineyards

## Summary Functions and Maps

### Questão 6
Qual é a mediana da coluna `points` no DataFrame `reviews`?

In [ ]:
#@title Resposta Q6

def column_null_check(df, column_name):
  if df[column_name].isnull().values.any():
    print(f'Há valores nulos na coluna {column_name}.')
  else:
    print(f'Não há valores nulos na coluna {column_name}.')

column_null_check(wine_reviews, 'points')


median_points = wine_reviews['points'].median()
print(f'A mediana da coluna points é: {median_points}')

Não há valores nulos na coluna points.
A mediana da coluna points é: 88.0

### Questão 7
Quais são os países são representados no dataset? (a resposta não deve incluir qualquer duplicação).

In [ ]:
#@title Resposta Q7

paises = wine_reviews['country'].sort_values().unique()
for i in range(0, len(paises), 2):
    pais1 = paises[i]
    pais2 = paises[i+1] if i+1 < len(paises) else ""
    print(f'- {pais1:<35} - {pais2}')

- Argentina                           - Armenia
- Australia                           - Austria
- Bosnia and Herzegovina              - Brazil
- Bulgaria                            - Canada
- Chile                               - China
- Croatia                             - Cyprus
- Czech Republic                      - Egypt
- England                             - France
- Georgia                             - Germany
- Greece                              - Hungary
- India                               - Israel
- Italy                               - Lebanon
- Luxembourg                          - Macedonia
- Mexico                              - Moldova
- Morocco                             - New Zealand
- Peru                                - Portugal
- Romania                             - Serbia
- Slovakia                            - Slovenia
- South Africa                        - Spain
- Switzerland                         - Turkey
- US                                  - Ukraine
- Uruguay                             - nan

### Questão 8
Com que frequência cada país aparece no dataset? Crie uma Série `review_per_country` que mapeia países a contagem de reviews de vinhos daquele país.

In [ ]:
#@title Resposta Q8

freq_paises = wine_reviews['country'].value_counts()
freq_paises

country
US                        54504
France                    22093
Italy                     19540
Spain                      6645
Portugal                   5691
Chile                      4472
Argentina                  3800
Austria                    3345
Australia                  2329
Germany                    2165
New Zealand                1419
South Africa               1401
Israel                      505
Greece                      466
Canada                      257
Hungary                     146
Bulgaria                    141
Romania                     120
Uruguay                     109
Turkey                       90
Slovenia                     87
Georgia                      86
England                      74
Croatia                      73
Mexico                       70
Moldova                      59
Brazil                       52
Lebanon                      35
Morocco                      28
Peru                         16
Ukraine                      14
Serbia                       12
Czech Republic               12
Macedonia                    12
Cyprus                       11
India                         9
Switzerland                   7
Luxembourg                    6
Bosnia and Herzegovina        2
Armenia                       2
Slovakia                      1
China                         1
Egypt                         1
Name: count, dtype: int64

### Questão 9
Crie uma variável `centered_price` contendo uma versão da coluna `price` com o preço médio subtraído.
Nota: esta transformação chamada 'centralização´ é uma etapa de pré-processamento sobre um dataset anterior e aplicada a vários algoritmos de machine learning.

In [ ]:
#@title Resposta Q9

wine_reviews_drop = wine_reviews.dropna(subset=['price'])

mean_price = wine_reviews_drop['price'].mean()
centered_price = wine_reviews_drop['price'] - mean_price
centered_price

1        -20.363389
2        -21.363389
3        -22.363389
4         29.636611
5        -20.363389
            ...
129966    -7.363389
129967    39.636611
129968    -5.363389
129969    -3.363389
129970   -14.363389
Name: price, Length: 120975, dtype: float64

### Questão 10
Suponha que você seja um comprador assíduo de vinhos. Que vinho é considerado a melhor pechincha? Crie uma variável `bargain_wine` com o título de vinhos que apresentam a razão entre pontos-e-preço mais elevada no dataset.

In [ ]:
#@title Resposta Q10 - Razão

list_of_bargain_wines = []
for i in range(len(wine_reviews)):
  list_of_bargain_wines.append(wine_reviews.loc[i, 'points'] / wine_reviews.loc[i, 'price']) # Para cada linha, calcula a razão entre pontos e preço

wine_reviews['bargain_points_price'] = list_of_bargain_wines
bargain_wine = wine_reviews.loc[wine_reviews['bargain_points_price'] == wine_reviews['bargain_points_price'].max()] # Retorna apenas as linhas onde a razão é igual ao valor máximo
bargain_wine

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,bargain_points_price
64590,US,"There's a lot going on in this Merlot, which i...",NaN,86,4.0,California,California,California Other,NaN,NaN,Bandit NV Merlot (California),Merlot,Bandit,21.5
126096,Romania,Notes of sun-dried hay and green flower highli...,UnWineD,86,4.0,Viile Timisului,NaN,NaN,Anna Lee C. Iijima,NaN,Cramele Recas 2011 UnWineD Pinot Grigio (Viile...,Pinot Grigio,Cramele Recas,21.5

In [ ]:
#@title Resposta Q10 - Mediana
# w = 0 # @param {"type":"number"}

price_median = wine_reviews['price'].median()
points_median = wine_reviews['points'].median()

print(f'\nConsiderando uma mediana de preço de {price_median:.2f} e uma mediana pontos de {points_median:.2f}, os vinho de maior barganha são:\n')

bargain_wine = wine_reviews.loc[(wine_reviews['price'] < price_median) & (wine_reviews['points'] > points_median)]
bargain_wine.sort_values(by='price', ascending=True)

Considerando uma mediana de preço de 25.00 e uma mediana pontos de 88.00, os vinho de maior barganha são:

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,bargain_points_price
95728,Portugal,"This is a herbal, earthy wine with as many tan...",D. Fuas Reserva,89,7.0,Terras do Dão,NaN,NaN,Roger Voss,@vossroger,Caves Velhas 2013 D. Fuas Reserva Red (Terras ...,Portuguese Red,Caves Velhas,12.714286
42891,Spain,"On the spot and sweet, with black cherry and r...",Monte Oton,89,7.0,Northern Spain,Campo de Borja,NaN,Michael Schachner,@wineschach,Borsao 2008 Monte Oton Garnacha (Campo de Borja),Garnacha,Borsao,12.714286
63697,US,"Tart and juicy, this Cabernet/Merlot/Syrah ble...",Red Table Wine,89,7.0,Washington,Columbia Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Hogue 2008 Red Table Wine Red (Columbia Valley...,Red Blend,Hogue,12.714286
34629,Portugal,"Richly tannic, this concentrated wine has grea...",Toutalga,91,7.0,Alentejano,NaN,NaN,Roger Voss,@vossroger,Herdade dos Machados 2012 Toutalga Red (Alente...,Portuguese Red,Herdade dos Machados,13.000000
70687,Portugal,This wine remains a benchmark for the Vinho Ve...,Quinta da Aveleda Estate Bottled Loureiro-Alva...,90,8.0,Minho,NaN,NaN,Roger Voss,@vossroger,Aveleda 2013 Quinta da Aveleda Estate Bottled ...,Portuguese White,Aveleda,11.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11735,US,"As in earlier vintages, this is three quarters...",NaN,89,24.0,Oregon,Walla Walla Valley (OR),Oregon Other,Paul Gregutt,@paulgwine,Watermill 2007 Cabernet Sauvignon (Walla Walla...,Cabernet Sauvignon,Watermill,3.708333
74205,US,There's a lot to like in this vineyard-designa...,Peterson Vineyard,89,24.0,California,Sonoma Valley,Sonoma,Virginie Boone,@vboone,Deerfield 2014 Peterson Vineyard Sauvignon Bla...,Sauvignon Blanc,Deerfield,3.708333
74290,US,The translucent color and light body warn agai...,NaN,90,24.0,California,Napa Valley,Napa,NaN,NaN,Waterstone 2009 Cabernet Sauvignon (Napa Valley),Cabernet Sauvignon,Waterstone,3.750000
113070,US,"This is a bold, very ripe and full-bodied wine...",Radix Vinea,92,24.0,California,El Dorado,Sierra Foothills,Jim Gordon,@gordone_cellars,Uvaggio 2015 Radix Vinea Zinfandel (El Dorado),Zinfandel,Uvaggio,3.833333
38961,US,"This dry wine from the Ribbon Ridge vineyard, ...",Ribbon Ridge Estate Dry,94,24.0,Oregon,Ribbon Ridge,Willamette Valley,Paul Gregutt,@paulgwine,Trisaetum 2013 Ribbon Ridge Estate Dry Rieslin...,Riesling,Trisaetum,3.916667

In [ ]:
#@title Resposta Q10 - Abordagem Gráfica

import plotly.express as px

fig = px.scatter(wine_reviews, x='points', y='price', title='Pontos vs Preço', color='variety', labels={'points': 'Pontos', 'price': 'Preço', 'variety': 'Variedade'})
fig.show()

### Questão 11
Há muita palavras que podemos usar para descrever uma garrafa de vinho. Um vinho é mais provável ser "tropical" ou "fruity"? Crie uma Series chamada `descriptor_counts` que armazene quantas vezes cada uma dessas palavras aparecem na coluna `description`. (Por razões de simplicidade, ignore as versões em maiúsculas dessas palavras).

In [ ]:
#@title Resposta Q11

tropical_count = wine_reviews['description'].map(lambda desc: 'tropical' in desc).sum()
fruity_count = wine_reviews['description'].map(lambda desc: 'fruity' in desc).sum()

descriptor_counts = pd.Series([tropical_count, fruity_count], index=['tropical', 'fruity'])
descriptor_counts

tropical    3607
fruity      9090
dtype: int64

### Questão 12
Suponha que gostaríamos de traduzir o sistema atual de pontos para um sistema de notas mais simplificado. Um vinho com score de 95 ou mais receberia 3 estrelhas, um score de pelo menos 85 e não menos que 95 receberia 2 estrelas. Qualquer outro score de pontos recebe 1 estrela.

Crie uma séries `star_ratings` com o número de estrelas correspondendo a cada review no dataset.

In [ ]:
#@title Resposta Q12

def stars(row):
    if row.points >= 95:
        return 3
    elif row.points >= 85:
        return 2
    else:
        return 1

star_ratings = wine_reviews.apply(stars, axis='columns')
star_ratings

0         2
1         2
2         2
3         2
4         2
         ..
129966    2
129967    2
129968    2
129969    2
129970    2
Length: 129971, dtype: int64

## Grouping and Sorting

### Questão 13
Crie uma `Series` cujo os índices é um revisor (`reviewers`) e cujo os valores é o score médio de revisão dado por aquele revisor. Dica: você precisa utlizar as colunas `taster_name` e `points`.

Em seguida, compare o score médio de revisão atribuído pelos vários revisores e o score médio global do dataset.

In [ ]:
#@title Resposta Q13

global_mean_points = wine_reviews['points'].mean()
print(f"\nO score médio global é: {global_mean_points:.2f}\n")

reviewer_mean_points = wine_reviews.groupby('taster_name')['points'].mean()
reviewer_mean_points = reviewer_mean_points.dropna()
reviewer_mean_points = reviewer_mean_points.sort_values(ascending=False)

reviewer_mean_points_diff = reviewer_mean_points - global_mean_points

reviewer_stats = pd.DataFrame({'Mean Points': reviewer_mean_points, 'Global Mean Diff.': reviewer_mean_points_diff})
reviewer_stats.reset_index(inplace=True)
reviewer_stats.rename(columns={'taster_name': 'Reviewer'}, inplace=True)
reviewer_stats

O score médio global é: 88.45

              Reviewer  Mean Points  Global Mean Diff.
0     Anne Krebiehl MW    90.562551           2.115413
1        Matt Kettmann    90.008686           1.561548
2       Virginie Boone    89.213379           0.766241
3        Mike DeSimone    89.101167           0.654029
4         Paul Gregutt    89.082564           0.635426
5        Kerin O’Keefe    88.867947           0.420809
6     Sean P. Sullivan    88.755739           0.308601
7           Roger Voss    88.708003           0.260865
8           Jim Gordon    88.626287           0.179149
9       Joe Czerwinski    88.536235           0.089096
10  Anna Lee C. Iijima    88.415629          -0.031510
11        Jeff Jenssen    88.319756          -0.127383
12   Christina Pickard    87.833333          -0.613805
13       Lauren Buzzeo    87.739510          -0.707629
14   Michael Schachner    86.907493          -1.539645
15         Fiona Adams    86.888889          -1.558249
16     Susan Kostrzewa    86.609217          -1.837922
17        Carrie Dykes    86.395683          -2.051455
18  Alexander Peartree    85.855422          -2.591717

### Questão 14

Qual é o melhor vinho que eu posso comprar dada uma quantia de dinheiro? Crie uma `Series` onde os índices são os preços e os valores é o número máximo de pontos que um que um vinho com aquele custo foi dado em uma avaliação.

In [ ]:
#@title Resposta Q14

wine_reviews.groupby('price')['points'].max()

price
4.0       86
5.0       87
6.0       88
7.0       91
8.0       91
          ..
1900.0    98
2000.0    97
2013.0    91
2500.0    96
3300.0    88
Name: points, Length: 390, dtype: int64

## Data Types and Missing Values

### Questão 15
Alguns preços da coluna `price` são null. Quantas reviews no dataset está com valores de price ausentes?

In [ ]:
#@title Resposta Q15

column_null_check(wine_reviews, 'price')
null_count = wine_reviews['price'].isnull().sum()
print(f'Há {null_count} reviews com valores de preço ausentes.')

Há valores nulos na coluna price.
Há 8996 reviews com valores de preço ausentes.

### Questão 16

Quais são as regiões produtoras de vinhos mais populares? Crie uma `Series` que contam o número de vezes que cada valor ocorre no campo `region_1`. Como esse campo costume ter valores ausentes, substitua os valores ausentes por `Unknown`. Em seguida, ordene de forma decrecente.

In [ ]:
#@title Resposta Q16

wine_reviews['region_1'] = wine_reviews['region_1'].fillna('Unknown')
wine_reviews['region_1'].value_counts().sort_values(ascending=False)

region_1
Unknown                 21247
Napa Valley              4480
Columbia Valley (WA)     4124
Russian River Valley     3091
California               2629
                        ...
Offida Rosso                1
Corton Perrières            1
Isle St. George             1
Geelong                     1
Paestum                     1
Name: count, Length: 1230, dtype: int64

## Renaming and Combining

### Questão 17

`region_1` e `region_2` são colunas cujos os nomes poucos informativos para localidade. Crie uma cópia do dataframe wine_reviews com estas colunas renomeadas para `region` e `locale`, respectivamente.

In [ ]:
#@title Resposta Q17

wine_reviews.rename(columns={'region_1': 'region', 'region_2': 'locale'}, inplace=True)
wine_reviews[['region', 'locale']].head()

                region             locale
0                 Etna                NaN
1              Unknown                NaN
2    Willamette Valley  Willamette Valley
3  Lake Michigan Shore                NaN
4    Willamette Valley  Willamette Valley